### ISSUE TITLE
Patching of custom security attribute is failing with error TypeError: Encountered an unknown type during serialization <class 'dict'>

### ISSUE THREAD

**Issue by cynepco3hahue** [microsoft/kiota-python#357]
**Environment**

- Python Version `3.10`
- kiota-serialization-json version: `microsoft-kiota-serialization-json   1.1.0`
- OS: `amazonlinux:2`

**Stack trace (if available)**
```
[2024-03-10 14:25:30,457 microsoft/kiota-serialization-json-python#80] INFO: HTTP Request: GET https://graph.microsoft.com/v1.0/servicePrincipals?$top=1&$filter=startswith%28displayName%2C%20%27core-stg6-user-app%27%29&$count=true&$orderby=displayName "HTTP/2 200 OK"
[2024-03-10 14:25:31,855 microsoft/kiota-serialization-json-python#80] INFO: HTTP Request: GET https://graph.microsoft.com/v1.0/servicePrincipals/806a7c55-cbc0-4399-81f5-6df0a73c98a8?$select=customSecurityAttributes "HTTP/2 200 OK"
CustomSecurityAttributeValue(additional_data={'recoverbyok': {'@odata.type': '#microsoft.graph.customSecurityAttributeValue', 'readonly@odata.type': '#Collection(String)', 'readonly': ['stg6-a-9000632-927f4b', 'stg6-a-9000617-3d2e13', 'stg6-a-9000618-9d0710', 'stg6-a-9000620-501d69', 'stg6-a-9000621-3a48cb', 'stg6-a-9000638-ae6e32']}}, odata_type=None)
Patch dict CustomSecurityAttributeValue(additional_data={'recoverbyok': {'@odata.type': '#microsoft.graph.customSecurityAttributeValue', 'readonly@odata.type': '#Collection(String)', 'readonly': ['stg6-a-9000632-927f4b', 'stg6-a-9000617-3d2e13', 'stg6-a-9000618-9d0710', 'stg6-a-9000620-501d69', 'stg6-a-9000621-3a48cb', 'stg6-a-9000638-ae6e32', 'stg6-a-9000641-74553d']}}, odata_type=None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/cloud_accessors/common/exception/exception_handler.py", line 59, in azure_exception_handler
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/cloud_accessors/identity_access_manager/azure/identity_access_manager.py", line 111, in add_value_to_service_principal_custom_security_attribute
    self._patch_service_principal_custom_security_attributes(
  File "/usr/local/lib/python3.10/site-packages/cloud_accessors/identity_access_manager/azure/identity_access_manager.py", line 65, in _patch_service_principal_custom_security_attributes
    self._event_loop.run_until_complete(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/msgraph/generated/service_principals/item/service_principal_item_request_builder.py", line 108, in patch
    request_info = self.to_patch_request_information(
  File "/usr/local/lib/python3.10/site-packages/msgraph/generated/service_principals/item/service_principal_item_request_builder.py", line 173, in to_patch_request_information
    request_info.set_content_from_parsable(self.request_adapter, "application/json", body)
  File "/usr/local/lib/python3.10/site-packages/kiota_abstractions/request_information.py", line 179, in set_content_from_parsable
    writer.write_object_value(None, values)
  File "/usr/local/lib/python3.10/site-packages/kiota_serialization_json/json_serialization_writer.py", line 285, in write_object_value
    self._serialize_value(temp_writer, value)
  File "/usr/local/lib/python3.10/site-packages/kiota_serialization_json/json_serialization_writer.py", line 462, in _serialize_value
    value.serialize(temp_writer)
  File "/usr/local/lib/python3.10/site-packages/msgraph/generated/models/service_principal.py", line 289, in serialize
    writer.write_object_value("customSecurityAttributes", self.custom_security_attributes)
  File "/usr/local/lib/python3.10/site-packages/kiota_serialization_json/json_serialization_writer.py", line 285, in write_object_value
    self._serialize_value(temp_writer, value)
  File "/usr/local/lib/python3.10/site-packages/kiota_serialization_json/json_serialization_writer.py", line 462, in _serialize_value
    value.serialize(temp_writer)
  File "/usr/local/lib/python3.10/site-packages/msgraph/generated/models/custom_security_attribute_value.py", line 47, in serialize
    writer.write_additional_data_value(self.additional_data)
  File "/usr/local/lib/python3.10/site-packages/kiota_serialization_json/json_serialization_writer.py", line 330, in write_additional_data_value
    self.write_any_value(key, val)
  File "/usr/local/lib/python3.10/site-packages/kiota_serialization_json/json_serialization_writer.py", line 451, in write_any_value
    raise TypeError(
TypeError: Encountered an unknown type during serialization <class 'dict'>                     with key recoverbyok
```

**Describe the bug**
Patching of custom security attribute is failing with above traceback
The input for pathing is
```
CustomSecurityAttributeValue(additional_data={'recoverbyok': {'@odata.type': '#microsoft.graph.customSecurityAttributeValue', 'readonly@odata.type': '#Collection(String)', 'readonly': ['stg6-a-9000632-927f4b', 'stg6-a-9000617-3d2e13', 'stg6-a-9000618-9d0710', 'stg6-a-9000620-501d69', 'stg6-a-9000621-3a48cb', 'stg6-a-9000638-ae6e32', 'stg6-a-9000641-74553d']}}, odata_type=None)
```

**To Reproduce**

**Expected behavior**
It should work as it worked under version 1.0.1

**Screenshots**

**Additional context**

**Comment by andrueastman** [comment]
@cynepco3hahue, @osolmaz  and @MaxNad Any chance you can confirm if this is still an issue?

I believe support for dictionaries was added in serialization in https://github.com/microsoft/kiota-serialization-json-python/pull/329 and https://github.com/microsoft/kiota-serialization-json-python/pull/335 so using a version of the json serialization library higher than 1.3.0 should have the implementation.
